use sakila;

-- 1.List the number of films per category.

SELECT * FROM category;
SELECT * FROM film_category;

SELECT category.name, COUNT(film_category.film_id)
FROM category
JOIN film_category ON category.category_id = film_category.category_id
GROUP BY category.name;


-- 2.Retrieve the store ID, city, and country for each store.


SELECT store.store_id, city.city, country.country
FROM store
JOIN address ON store.address_id = address.address_id
JOIN city ON address.city_id = city.city_id
JOIN country ON city.country_id = country.country_id;


-- 3.Calculate the total revenue generated by each store in dollars.

SELECT store.store_id, SUM(payment.amount) AS total_revenue
FROM store
JOIN staff ON store.store_id = staff.store_id
JOIN payment ON staff.staff_id = payment.staff_id
GROUP BY store.store_id;

-- another solution

SELECT DISTINCT store_id, SUM(amount)
FROM store s
JOIN inventory i USING (store_id)
JOIN rental USING(inventory_id)
JOIN payment USING(rental_id)
GROUP BY store_id;

-- 4.Determine the average running time of films for each category.

SELECT * FROM category;
SELECT * FROM film;
SELECT * FROM film_category;

SELECT category.name AS film_category, AVG(film.length) AS average_running_time
FROM category
JOIN film_category ON category.category_id = film_category.category_id
JOIN film ON film_category.film_id = film.film_id
GROUP BY category.name;



